# Generated by Django 2.0.5 on 2018-12-04 21:17

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatRooms',
            fields=[
                ('idmsg', models.AutoField(primary_key=True, serialize=False)),
                ('userOne', models.IntegerField()),
                ('userTwo', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
