# Generated by Django 2.0.5 on 2018-12-06 22:16

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messaging',
            fields=[
                ('idmsg', models.AutoField(primary_key=True, serialize=False)),
                ('idRoom', models.IntegerField()),
                ('senderId', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('idRoom', models.AutoField(primary_key=True, serialize=False)),
                ('idUser1', models.IntegerField()),
                ('idUser2', models.IntegerField()),
                ('created', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='chatRooms',
        ),
    ]
