# Generated by Django 2.0.5 on 2018-12-08 20:05

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('statut', models.IntegerField()),
                ('created', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
