# Generated by Django 2.0.5 on 2018-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='idUser',
            new_name='receiverId',
        ),
        migrations.AddField(
            model_name='friends',
            name='senderId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
